server:
  port: 8080

spring:
  # 加载配置文件
  profiles:
    # 加载application-druid.yml配置文件
    active: druid

  # 全局日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # redis配置
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    # 不要改为0，修改为5000合适
    timeout: 5000
    jedis:
      pool:
        max-wait: -1
        max-idle: 8
        min-idle: 0


  data:
    # ElasticSearch配置
    elasticsearch:
      # elasticsearch集群名称，默认的是elasticsearch
      cluster-name: docker-cluster
      #节点的地址 注意api模式下端口号是9300，千万不要写成9200
      cluster-nodes: 192.168.200.110:9300
      repositories:
        # 是否开启本地存储
        enabled: true


  # thymeleaf配置
  thymeleaf:
    cache: false
    check-template: false
    encoding: utf-8
    mode: HTML

  # SpringBoot上传文件大小限制
  servlet:
    multipart:
      # 默认是1MB，-1为不限制
      max-file-size: -1
      # 默认是10MB，-1为不限制
      max-request-size: -1


# mybatis
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.lzhpo.aurora.admin.entity
  config-location: classpath:/mybatis/mybatis-config.xml

# PageHelper分页插件
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql

##########################################################自定义配置#############################################################
# 在线发送邮件配置
myEmail:
  # 是否开启debug发送邮件
  debug: true
  # 发件人的邮箱
  username:
  # 发件人的邮箱密码（注意是授权码）
  password:

# 是否启用ES查询数据？true/false
ES:
  Enable: false